### ISSUE TITLE
Can not make a .py file and call function from cpp file

### ISSUE THREAD

**Issue by jmo2014** [tiger-punch-sports-club/pybind11-tutorial#1]
Hello, have you encountered the problem that python file can not call function from cpp file? When I try to do that, the console tells me that No module named XXX. By the way, I use MacOS. Don't know if the same problem occurs in windows?

**Comment by polygonboutique** [comment]
I downloaded the project from GitHub and compiled it on MacOS.
First I also got the same error message as you, when I tried to import the module into Python.
For me the problem was that I had a version mismatch. The module got compiled with Python3 and I was trying to load it with Python2.7.

Could you please try importing the module with Python3?
In terminal run "python3" instead of "python".

<img width="770" alt="screenshot terminal" src="https://user-images.githubusercontent.com/6142529/97892526-67150a80-1d30-11eb-9e43-614ede138fb2.png">
